ebook/urls.py
from django.urls import path
from . import views as store_views



urlpatterns = [
    path('', store_views.home, name='bookstore-home'),
    path('product/<slug>/',store_views.ItemDetailView.as_view(), name='product-detail'),
    path('order-summary/', store_views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', store_views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', store_views.remove_from_cart, name='remove-from-cart'),
    path('add-to-wishlist/<slug>/', store_views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist/<slug>/', store_views.remove_from_wishlist, name='remove-from-wishlist'),
    path('my-wishlist/', store_views.my_wishlist, name='my-wishlist'),
    path('remove-single-item-from-cart/<slug>/', store_views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('add-coupon/', store_views.AddCouponView.as_view(), name='add-coupon'),
    path('author/<str:author>/', store_views.AuthorBookList, name='author-books'),
    path('category/<str:category>/', store_views.CategoryBookList, name='category-books'),
    path('tag/<slug:slug>/', store_views.tagged, name='tagged'),
    path('add-book/', store_views.add_book, name='add-book'),
    path('my-orders/', store_views.my_orders, name='my-orders'),
    path('profile/', store_views.profile, name='profile'),
    path('add-seller/', store_views.add_seller, name='add-seller'),
    path('about-us/', store_views.about_us, name="about-us"),
    path('terms-and-conditions/', store_views.terms_and_conditions, name="terms-and-conditions"),
    path('privacy/', store_views.privacy, name="privacy"),
    path('refunds-cancellation/', store_views.refunds_cancellation, name="refunds-cancellation"),
    path('update-book/<slug>/', store_views.update_book, name='update-book'),
    path('order-placed/<payment_id>/', store_views.order_placed, name='order-placed'),
    path('seller-order-details/<payment_id>/', store_views.seller_order_details, name="seller_order_details"),
    path('request-refund/<payment_id>/', store_views.request_refund, name="request-refund"),
    path('grant-refund/<payment_id>/', store_views.grant_refund, name="grant-refund"),
    path('my-orders/', store_views.my_orders, name='my-orders'),
    path('seller-sale/', store_views.seller_sale, name="seller-sale"),
    path('checkout/', store_views.CheckoutView.as_view(), name='checkout'),
    path('refunds-cancellation/', store_views.refunds_cancellation, name="refunds-cancellation"),
    path('payment/', store_views.payment, name='payment'),
    path('payment-success/', store_views.payment_success, name='payment-success'),
    path('add-seller/', store_views.add_seller, name='add-seller'),
    path('seller-books/', store_views.SellerBooks.as_view(), name='seller-books'),
    path('add-referal/', store_views.AddReferalView.as_view(), name='add-referal'),
    path('search-result/<str:search>/', store_views.search_result, name="search-result"),
    path('activate-sellers-account/', store_views.activate_sellers_account, name='activate-sellers-account'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('ebook.urls')),
]

ebook/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from .models import Book, Seller, User

CATEGORY_CHOICES = (
   ('Historical', 'Historical'),
    ('Horror', 'Horror'),
    ('Romance', 'Romance'),
    ('Suspense','Suspense'),
)

LANGUAGES = {
    ('English', 'English'),
}

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

SIDE_PANEL_POSITION_CHOICES = {
    ('first_image', 'first_image'),
    ('second_image', 'second_image'),
    ('yt_video_link', 'yt_video_link'),
}


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=True)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=True,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=True)

    billing_address = forms.CharField(required=True)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=True,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=True)

    bstate = forms.CharField(required=True)
    bcity = forms.CharField(required=True)
    bdistrict = forms.CharField(required=True)
    sstate = forms.CharField(required=True)
    scity = forms.CharField(required=True)
    sdistrict = forms.CharField(required=True)
    firstname = forms.CharField(required=True)
    lastname = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone_number = forms.IntegerField(required=True)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    # payment_option = forms.ChoiceField(
    #     widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))

class ReferalForm(forms.Form):
    rcode = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Referal Code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'title',
            'author',
            'price',
            'discount_price',
            'description',
            'category',
            'language',
            'tags',
            'image',
            'weight',
        ]

class AddSellerForm(forms.Form):
    phone_number = forms.IntegerField()

class BookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'title',
            'author',
            'price',
            'discount_price',
            'description',
            'category',
            'language',
            'tags',
            'image',
            'weight',
        ]


class UserUpdateForm(forms.Form):
    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

class ActivateSellerForm(forms.Form):
    ref_code = forms.CharField()

templates/bookstore/activate_sellers_account.html
{% extends "bookstore/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

  <main class="mt-5 pt-4">
    <div class="container">

      
        <div class="card bg-secondary mb-3">
          <h2 class="my-1 h2 text-center" style="color: white;">Activate your sellers account</h2>
        </div>
      
      <div class="row">
        <div class="col-md-12 mb-4">
          <div class="card">
            <div class="form-group">
              <form method="POST">
                {% csrf_token %}
                <div id="div_id_ref_code" class="form-group">
                  <label for="id_ref_code" class="">Enter Your Activation Code</label><span class="asteriskField">*</span>
                  <div class=""> 
                    <input type="ref_code" name="ref_code" placeholder="Enter Your Activation Code" maxlength="254" class="form-control" id="id_ref_code"> 
                  </div> 
                </div>
                <button class="btn btn-secondary"> Activate </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}

templates/bookstore/add_book_deatils.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="css/mdb.min.css" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="css/style.min.css" rel="stylesheet">
</head>

<body class="grey lighten-3">

    <!--Main layout-->
    <main class="mt-3 pt-3 mb-3 pb-3">
        <div class="container wow fadeIn">

            <!-- Heading -->
            <h2 class="my-5 h2 text-center">Sellers' form</h2>

                    <!--Card-->
                    <div class="card pl-5 pr-5">

                        <!--Card content-->
                        <form class="card-body">

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-md-6 mb-2">

                                    <!--firstName-->
                                    <div class="md-form ">
                                        <input type="text" id="firstName" class="form-control">
                                        <label for="firstName" class="">Title</label>
                                    </div>

                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-md-6 mb-2">

                                    <!--lastName-->
                                    <div class="md-form">
                                        <input type="text" id="lastName" class="form-control">
                                        <label for="lastName" class="">Author</label>
                                    </div>

                                </div>
                                <!--Grid column-->

                            </div>
                            <!--Grid row-->

                            <!--Username-->
                            <div class="md-form input-group pl-0 mb-5">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">@</span>
                                </div>
                                <input type="text" class="form-control py-0" placeholder="Username (optional)"
                                    aria-describedby="basic-addon1">
                            </div>

                            <!--email-->
                            <div class="md-form mb-5">
                                <input type="text" id="email" class="form-control" placeholder="youremail@example.com">
                                <label for="email" class="">Email (optional)</label>
                            </div>

                            <!--address-->
                            <div class="md-form mb-5">
                                <input type="text" id="address" class="form-control" placeholder="Your Name">
                                <label for="address" class="">Seller Name</label>
                            </div>

                            <!--address-->
                            <div class="md-form mb-5">
                                <input type="text" id="address" class="form-control" placeholder="Main St">
                                <label for="address" class="">Address</label>
                            </div>

                            <!--address-->
                            <div class="md-form mb-5">
                                <input type="text" id="address" class="form-control" placeholder="Main St">
                                <label for="address" class="">Address 2 (optional)</label>
                            </div>

                            <!-- phone no. -->
                            <div class="form-outline mb-5">
                                <label class="form-label" for="typePhone">Phone Number</label>
                                <input type="tel" id="typePhone" class="form-control" />
                            </div>

                            <!-- phone no. -->
                            <div class="form-outline mb-5">
                                <label class="form-label" for="typePhone">Phone Number (optional)</label>
                                <input type="tel" id="typePhone" class="form-control" />
                            </div>

                            <!-- Description -->
                            <div class="md-form mb-5">
                                <div class="form-outline">
                                    <h4>Description</h4>
                                    <textarea class="form-control pl-3" id="textAreaExample" rows="4"></textarea>
                                </div>
                            </div>




                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-12 mb-4">

                                    <label for="language">Language</label>
                                    <select class="custom-select d-block w-100" id="language" required>
                                        <option value="">Choose...</option>
                                        <option>Hindi</option>
                                        <option>English</option>
                                        <option>Urdu</option>
                                        <option>Odia</option>
                                        <option>Telugu</option>
                                        <option>Bengali</option>
                                    </select>
                                    <div class="invalid-feedback">
                                        Please select a valid Language.
                                    </div>

                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-6 mb-4">

                                    <label for="state">Category</label>
                                    <select class="custom-select d-block w-100" id="Category" required>
                                        <option value="">Choose...</option>
                                        <option>#</option>
                                        <option>#</option>
                                        <option>#</option>
                                        <option>#</option>
                                        <option>#</option>
                                    </select>
                                    <div class="invalid-feedback">
                                        Please provide a valid state.
                                    </div>

                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-6 mb-4">

                                    <label for="Pin">Pin Code</label>
                                    <input type="text" class="form-control" id="zip" placeholder="" required>
                                    <div class="invalid-feedback">
                                        Pin code required.
                                    </div>

                                </div>
                                <!--Grid column-->

                            </div>
                            <!--Grid row-->

                            <hr>

                            <!-- Tags -->
                            <div class="d-block my-3">
                            <h5>Tags</h5>
                            <div class="form-check">

                                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" />
                                <label class="form-check-label" for="flexCheckDefault">
                                    checkbox
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" />
                                <label class="form-check-label" for="flexCheckChecked">
                                    checkbox
                                </label>
                            </div>
                    </div>

                    <hr>

                    <div class="d-block my-3">
                        <div class="custom-control custom-radio">
                            <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked
                                required>
                            <label class="custom-control-label" for="credit">sdasf</label>
                        </div>
                        <div class="custom-control custom-radio">
                            <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                            <label class="custom-control-label" for="debit">efefefe</label>
                        </div>
                        <div class="custom-control custom-radio">
                            <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                            <label class="custom-control-label" for="paypal">efef</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="cc-name">Price of the book</label>
                            <input type="text" class="form-control" id="cc-name" placeholder="" required>
                            <small class="text-muted">M.R.P</small>
                            <div class="invalid-feedback">
                                Price of the book is required!
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="cc-number">Discount price of the book</label>
                            <input type="text" class="form-control" id="cc-number" placeholder="" required>
                            <div class="invalid-feedback">
                                Discount price of the book is required!
                            </div>
                        </div>
                    </div>
                    
                    
                    <button class="btn btn-primary btn-lg btn-block mb-4 mt-2" type="submit">Continue to checkout</button>

                    </form>

                </div>
                <!--/.Card-->

            


        

        </div>
    </main>
    <!--Main layout-->



    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="js/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="js/mdb.min.js"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>
</body>

</html>

templates/bookstore/add_seller.html
{% extends "bookstore/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

  <main class="mt-5 pt-4">
    <div class="container">

      
        <div class="card bg-secondary mb-3">
          <h2 class="my-1 h2 text-center" style="color: white;">Become a Seller</h2>
        </div>
      
      <div class="row">
        <div class="col-md-12 mb-4">
          <div class="card p-5">
            <div class="form-group">
              <form method="POST">
                {% csrf_token %}
                
                <div id="div_id_username" class="form-group"> 
                  <label for="id_username" class="">Username</label><span class="asteriskField">*</span>
                  <div class=""> 
                    <input type="username" name="username" value="{{ user_details.username }}" maxlength="254" class="form-control" id="id_username"> 
                  </div> 
                </div>
                <div id="div_id_email" class="form-group"> 
                  <label for="id_email" class="">Email address</label><span class="asteriskField">*</span>
                  <div class=""> 
                    <input type="email" name="email" value="{{ user_details.email }}" maxlength="254" class="emailinput form-control" id="id_email"> 
                  </div> 
                </div>
                <div id="div_id_first_name" class="form-group"> 
                  <label for="id_first_name" class="">First Name</label><span class="asteriskField">*</span>
                  <div class=""> 
                    <input type="first_name" name="first_name" value="{{ user_details.first_name }}" maxlength="254" class="emailinput form-control" id="id_first_name"> 
                  </div> 
                </div>
                <div id="div_id_last_name" class="form-group"> 
                  <label for="id_last_name" class="">Last Name</label><span class="asteriskField">*</span>
                  <div class=""> 
                    <input type="last_name" name="last_name" value="{{ user_details.last_name }}" maxlength="254" class="emailinput form-control" id="id_last_name"> 
                  </div> 
                </div>
                <label for="id_phone_number col-auto" class="">Phone Number</label><span class="asteriskField">*</span>
                {{ form.phone_number}}
                <br>
                <button class="btn btn-success btn-sm py-0 btn-block mt-4"><h4 class="pt-2"> Submit </h4></button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}

templates/bookstore/loader.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>loader</title>
    <link rel="stylesheet" href="loader.css">
</head>
<body>
    <!-- loader -->
  <div class="container-load">
    <div class="dot dot-1"></div>
    <div class="dot dot-2"></div>
    <div class="dot dot-3"></div>
  </div>
  
  <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
    <defs>
      <filter id="goo">
        <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
        <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 21 -7"/>
      </filter>
    </defs>
  </svg>
  <!-- loader -->
</body>
</html>

templates/bookstore/loader2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>loader2</title>
    <link rel="stylesheet" href="loader2.css">
</head>
<body>
    <div class="container-load2">
        <div class="yellow"></div>
        <div class="red"></div>
        <div class="blue"></div>
        <div class="violet"></div>
    </div>
</body>
</html>

templates/bookstore/payment.html
{% extends "bookstore/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<main class="mt-5">
  <div class="container mt-4">
    <div class="jumbotron card card-image"
      style="background-image: url(https://mdbootstrap.com/img/Photos/Others/gradient1.jpg);">
      <div class="text-white text-center py-5 px-4">
          <div class="table-responsive text-nowrap">
            Rs. {{ ramount }}
            {% comment %} <form><script src="https://checkout.razorpay.com/v1/payment-button.js" data-payment_button_id="pl_GM1ZNWQYu1SlIw"> </script> </form> {% endcomment %}
            <form action="/payment-success/" method="POST">
            <script
                {% comment %} src="https://checkout.razorpay.com/v1/payment-button.js" {% endcomment %}
                src="https://checkout.razorpay.com/v1/checkout.js"
                data-key={{ key_id }} // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                data-amount="{{ amount }}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                data-order_id="{{order.rp_order_id}}"//Replace with the order_id generated by you in the backend.
                data-buttontext="Pay with Razorpay"
                {% comment %} data-payment_button_id="pl_GM1ZNWQYu1SlIw" {% endcomment %}
                data-name="{{ order.firstname }}"
                data-description="Payment by {{ requesr.user.username }}"
                data-image="https://example.com/your_logo.jpg"
                data-prefill.name="{{ request.user.username }}"
                data-prefill.email="{{ order.email }}"
                data-prefill.contact="{{ order.phone_number }}"
                data-theme.color="#F37254"
            ></script>
            <input type="hidden" custom="Hidden Element" name="hidden">
            </form>
          </div>
      </div>
    </div>
  </div>
</main>



{% endblock content %}

{% block extra_scripts %}

{% endblock extra_scripts %}

templates/bookstore/refunds_cancellation.html
{% extends "bookstore/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<main class="m-lg-5" style="font-size: 1.5rem;">
  <div class="container shadow-3-strong pt-3 rounded">
    <div class="card bg-secondary mb-3">
      <h2 class="my-1 h2 text-center" style="color: white;">Refunds/ Cancellations</h2>
    </div>
    <div class="row p-lg-5 p-4 pl-5 ml-lg-1 ml-xl-1">
      
      <!-- mobile view -->
      <ul class="d-lg-none d-xl-none" style="font-size: 1rem;">
        <li>
          In case of any disputed transactions, refunds requests or cancellations, the customer is advised
          to directly get in touch with us on our official contact or email.
        </li>
        <br>
        <li>
          Any refunds will not be made
          until and unless the grievance of the user has been completely analyzed and deemed genuine.
        </li>
        <br>
        <li>
          All refunds will be released under 7 (working days) from the cancellation request.
        </li>
        <br>
        <li>
          Books will not be returned if torn, distorted or damaged otherwise and will be at the sole risk
          of the customer, Moreover the Academy will not pay (except the refund) for any postal charges made
          to return the books.
        </li>
      </ul>

      <!-- laptop view -->
      <ul class="d-lg-block d-md-block d-xl-block d-none">
        <li>
          In case of any disputed transactions, refunds requests or cancellations, the customer is advised
          to directly get in touch with us on our official contact or email.
        </li>
        <li>
          Any refunds will not be made
          until and unless the grievance of the user has been completely analyzed and deemed genuine.
        </li>
        <li>
          All refunds will be released under 7 (working days) from the cancellation request.
        </li>
        <li>
          Books will not be returned if torn, distorted or damaged otherwise and will be at the sole risk
          of the customer, Moreover the Academy will not pay (except the refund) for any postal charges made
          to return the books.
        </li>
      </ul>
    </div>
  </div>
</main>

{% endblock content %}

templates/bookstore/socialMediaLnks.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
<style>
#sociolnks a {
  position: absolute;
  right: -120px;
  transition: 0.3s;
  padding-top: 18px;
  padding-bottom: 15px;
  padding-left: 18px;
  width: 160px;
  text-decoration: none;
  font-size: 25px;
  color: white;
  border-radius: 5px 0px 0px 5px;
}

.fab {
	padding-right: 25px;
}

#sociolnks a:hover {
  right: 0;
}

#insta {
  top: 20px;
  background-color:  #cd486b;
}

#ytb {
  top: 85px;
  background-color: #FF0000;
}

#twt {
  top: 150px;
  background-color: #1DA1F2;
}

#fb {
  top: 215px;
  background-color: #4267B2
}

#ldn {
  top: 280px;
  background-color:  #0e76a8
}

#wtp {
  top: 345px;
  background-color:  #25D366
}
</style>
</head>
<body>

<div id="sociolnks">
  <a href="#" id="insta"><i class="fab fa-instagram white-text"></i>Instagram</a>
  <a href="#" id="ytb"><i class="fab fa-youtube white-text"></i>Youtube</a>
  <a href="#" id="twt"><i class="fab fa-twitter white-text"></i>Twitter</a>
  <a href="#" id="fb"><i class="fab fa-facebook-f white-text"></i>Facebook</a>
  <a href="#" id="ldn"><i class="fab fa-linkedin-in white-text"></i>Linkedin</a>
  <a href="#" id="wtp"><i class="fab fa-whatsapp white-text"></i>Whatsapp</a>
</div>


   
</body>
</html> 